/**
 * Render-time bilingual translation for student-facing dynamic content.
 *
 * Scope: gap-score evidence quotes, lesson-plan rationales, dashboard
 * summary blurbs — content that's generated by Claude at scoring time
 * in English and shown to a student whose native language may not be
 * English.
 *
 * Out of scope:
 *   - UI chrome (button labels, page titles) — those use the static
 *     dictionary in src/lib/i18n/dictionary.ts.
 *   - The actual English learning content (task prompts, transcripts,
 *     scenario bodies). The product *is* learning English; translating
 *     the test would defeat the assessment.
 *   - Employer-facing surfaces. The audit-grade record stays English.
 *
 * Implementation: server-side batched translation via Claude. One Claude
 * call per page render, translating all student-visible English strings
 * into the student's native_language at once. Cached in-process for the
 * request lifetime so the same string isn't translated twice.
 */

import Anthropic from "@anthropic-ai/sdk";
import { zodOutputFormat } from "@anthropic-ai/sdk/helpers/zod";
import { z } from "zod";
import {
  DEFAULT_LANGUAGE,
  isLanguageCode,
  type LanguageCode,
} from "./dictionary";

const MODEL = "claude-haiku-4-5-20251001";

export type Bilingual = {
  /** The student's native-language version (or the English original if
   *  translation isn't applicable / fails). */
  native: string;
  /** The original English string. Always present. */
  en: string;
  /** Whether `native` actually got translated (false when target is "en"
   *  or when translation fell through to a fallback). */
  translated: boolean;
};

export function isTranslatableLanguage(
  lang: string | null | undefined
): lang is LanguageCode {
  return isLanguageCode(lang) && lang !== DEFAULT_LANGUAGE;
}

const TranslationsSchema = z.object({
  translations: z
    .array(
      z.object({
        index: z.number().int().min(0),
        translated: z.string().min(1),
      })
    )
    .min(1),
});

function client() {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error("ANTHROPIC_API_KEY not configured");
  return new Anthropic({ apiKey });
}

const SYSTEM_PROMPT = `You are LingoPure's translation engine. You translate
short pieces of English business-coaching feedback (gap-score evidence,
lesson-plan rationales, dashboard summaries) into the student's native
language so they can understand what their AI coach has told them.

Rules:
- Preserve every quoted English phrase EXACTLY. Quoted phrases are
  what the student wrote or said and are evidence — they must not be
  translated. Wrap them in quotes in the target language too.
- Keep technical scoring vocabulary (CEFR bands like B2/C1, scores like
  "gap of 220") in English-Latin form, in line with how the student sees
  them on the dashboard.
- Match register: business-coaching tone, second person, clear and
  direct. Not formal officialese, not informal slang.
- Output ONLY the JSON object that matches the schema. Each translation
  in the same order as the input list, indexed.`;

const LANGUAGE_NAMES: Record<LanguageCode, string> = {
  en: "English",
  vi: "Vietnamese",
  tl: "Tagalog",
  id: "Indonesian",
  ms: "Malay",
  th: "Thai",
  km: "Khmer",
  lo: "Lao",
  my: "Burmese",
  ta: "Tamil",
  zh: "Mandarin Chinese (Simplified)",
};

/**
 * Translate a batch of English strings into target language. Returns an
 * array of the same length and order. Failures (no API key, model
 * error, malformed response) fall back to returning the English
 * originals so the caller never has to handle null.
 *
 * The cache key is (target, text). Same string twice in the same batch
 * → translated once, returned twice.
 */
export async function translateBatch(
  texts: string[],
  target: LanguageCode
): Promise<string[]> {
  if (texts.length === 0) return [];
  if (target === DEFAULT_LANGUAGE) return [...texts];

  // De-duplicate before sending — many evidence strings share boilerplate
  // (e.g. "Gap of …, baseline …") and translating once per unique value
  // saves tokens and keeps phrasing consistent across the page.
  const unique = Array.from(new Set(texts));
  const indexOf = new Map(unique.map((t, i) => [t, i]));

  let translatedUnique: string[];
  try {
    const anthropic = client();
    const langName = LANGUAGE_NAMES[target] ?? "the target language";
    const userMessage = [
      `Target language: ${langName}.`,
      "",
      "Translate each numbered item below. Quotes inside the text must stay in English.",
      "",
      ...unique.map((t, i) => `[${i}] ${t}`),
    ].join("\n");

    const r = await anthropic.messages.parse({
      model: MODEL,
      max_tokens: 2000,
      temperature: 0,
      system: [
        { type: "text", text: SYSTEM_PROMPT, cache_control: { type: "ephemeral" } },
      ],
      messages: [{ role: "user", content: userMessage }],
      output_config: { format: zodOutputFormat(TranslationsSchema) },
    });

    const parsed = r.parsed_output;
    if (!parsed) {
      console.warn("[i18n] translateBatch: model returned no parsed output");
      return [...texts];
    }
    translatedUnique = unique.map((original, i) => {
      const match = parsed.translations.find((t) => t.index === i);
      return match?.translated ?? original;
    });
  } catch (err) {
    console.warn(
      "[i18n] translateBatch failed, falling back to English:",
      err instanceof Error ? err.message : err
    );
    return [...texts];
  }

  // Map results back through the de-duplication.
  return texts.map((t) => {
    const idx = indexOf.get(t);
    return idx == null ? t : translatedUnique[idx];
  });
}

/**
 * Wrap a list of English strings into Bilingual pairs by calling
 * translateBatch once and pairing up. Convenience for pages that want
 * to pass a Bilingual[] straight to a render component.
 */
export async function bilingualize(
  texts: string[],
  target: LanguageCode | null | undefined
): Promise<Bilingual[]> {
  if (!target || !isTranslatableLanguage(target)) {
    return texts.map((en) => ({ native: en, en, translated: false }));
  }
  const translated = await translateBatch(texts, target);
  return texts.map((en, i) => ({
    native: translated[i] ?? en,
    en,
    translated: translated[i] !== en,
  }));
}
