-- 0016_phase_0b_battery.sql
-- ─────────────────────────────────────────────────────────────────────────────
-- Phase 0b assessment battery — schema prep.
--
-- Adds the three tables described in docs/phase-0b-assessment-battery.md
-- (discovery_task_prompts, discovery_task_responses, discovery_learning_signals)
-- plus the two new columns on gap_scores so a unified scorer can mark which
-- evidence stream produced each sub-score and which row is the canonical
-- one when both voice and battery evidence exist for the same skill.
--
-- Also drops two truly-dead artefacts from earlier iterations that have
-- zero references in src/ and scripts/:
--   - public.students_with_role (view, never queried)
--   - public.get_conversation_context() (RPC, never called)
--
-- This migration is purely additive on existing tables. No column drops on
-- tables that still have writes — those need code coordination and will
-- ship as 0017_cleanup.sql post-board-demo.
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── 1. Drop dead artefacts ─────────────────────────────────────────────────

drop view if exists public.students_with_role;
drop function if exists public.get_conversation_context(uuid);

-- ─── 2. gap_scores: source enum expansion + is_canonical ────────────────────

-- Expand the source CHECK constraint to include Phase 0b's new values.
-- The constraint is autogenerated as gap_scores_source_check.
alter table public.gap_scores
  drop constraint if exists gap_scores_source_check;
alter table public.gap_scores
  add constraint gap_scores_source_check
  check (source in (
    'discovery',        -- legacy: pre-Phase-0b voice-only scoring
    'lesson',
    'session',
    'exam',
    'voice_transcript', -- Phase 0b: extracted from the discovery call
    'battery_task'      -- Phase 0b: scored from a discovery_task_responses row
  ));

-- Marks the row a dashboard should display when multiple sources have
-- scored the same skill for the same student. The unified scorer
-- (Section 8 of the Phase 0b spec) sets exactly one row per skill to
-- true; the others stay false but remain queryable for audit.
alter table public.gap_scores
  add column if not exists is_canonical boolean not null default true;

-- ─── 3. discovery_task_prompts ──────────────────────────────────────────────
-- A bank of task prompts, role-scoped, versioned for re-test variants.
-- prompt_public is read-able by any authenticated user (the battery UI
-- needs it to render the task). prompt_private is service-role only —
-- it holds rubric anchors / correct answers that, if leaked, would let
-- a student game the score.

create table if not exists public.discovery_task_prompts (
  id uuid primary key default gen_random_uuid(),
  task_type text not null check (task_type in (
    'email_writing','listen_paraphrase','read_summarise','vocab_cloze'
  )),
  role_id uuid references public.roles(id) on delete set null,
  -- null role_id = generic prompt usable for any role
  difficulty_band text not null check (difficulty_band in
    ('A2','B1','B2','C1','C2')),
  variant_bucket text not null,
  -- Items in the same bucket are equivalent-difficulty so they can be
  -- swapped between attempt 1 and attempt N.
  prompt_public jsonb not null,
  prompt_private jsonb not null,
  is_archived boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists discovery_task_prompts_lookup_idx
  on public.discovery_task_prompts (task_type, difficulty_band, role_id)
  where is_archived = false;

alter table public.discovery_task_prompts enable row level security;

-- Authenticated users can read the public half of any non-archived prompt.
drop policy if exists "discovery_task_prompts_public_read"
  on public.discovery_task_prompts;
create policy "discovery_task_prompts_public_read"
  on public.discovery_task_prompts
  for select to authenticated
  using (is_archived = false);

-- prompt_private is column-level protected via a view + RLS policy that
-- denies the column to non-service-role. We achieve that here by
-- revoking column access; service role bypasses RLS so it still reads.
revoke select (prompt_private) on public.discovery_task_prompts
  from authenticated, anon;

-- ─── 4. discovery_task_responses ────────────────────────────────────────────
-- One row per task instance shown to a student. Resume = update the
-- existing row (unique constraint on student_id, task_type,
-- attempt_number) so refreshing the browser doesn't insert a duplicate.

create table if not exists public.discovery_task_responses (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  discovery_session_id uuid references public.discovery_sessions(id),
  task_prompt_id uuid not null references public.discovery_task_prompts(id),
  task_type text not null check (task_type in (
    'email_writing','listen_paraphrase','read_summarise','vocab_cloze'
  )),
  -- denormalised so the unique constraint can include it without a join
  attempt_number int not null default 1,
  -- attempt 1 = onboarding, 2+ = scheduled re-test
  started_at timestamptz not null default now(),
  submitted_at timestamptz,
  response_json jsonb not null,
  score int check (score is null or score between 0 and 1000),
  cefr_band text,
  evidence text,
  scored_at timestamptz,
  scoring_model text,
  -- so we can re-score on rubric updates
  created_at timestamptz not null default now(),
  unique (student_id, task_type, attempt_number)
);

create index if not exists discovery_task_responses_session_scored_idx
  on public.discovery_task_responses (discovery_session_id, scored_at);

create index if not exists discovery_task_responses_student_idx
  on public.discovery_task_responses (student_id, task_type);

alter table public.discovery_task_responses enable row level security;

-- Students can read and insert their own responses.
drop policy if exists "discovery_task_responses_self_select"
  on public.discovery_task_responses;
create policy "discovery_task_responses_self_select"
  on public.discovery_task_responses
  for select to authenticated
  using (student_id = auth.uid());

drop policy if exists "discovery_task_responses_self_insert"
  on public.discovery_task_responses;
create policy "discovery_task_responses_self_insert"
  on public.discovery_task_responses
  for insert to authenticated
  with check (student_id = auth.uid());

drop policy if exists "discovery_task_responses_self_update"
  on public.discovery_task_responses;
create policy "discovery_task_responses_self_update"
  on public.discovery_task_responses
  for update to authenticated
  using (student_id = auth.uid())
  with check (student_id = auth.uid());

-- Employer admins can read their cohort's responses via the existing
-- employer-scoping path (students.employer_id matches admin's employer).
drop policy if exists "discovery_task_responses_employer_read"
  on public.discovery_task_responses;
create policy "discovery_task_responses_employer_read"
  on public.discovery_task_responses
  for select to authenticated
  using (
    exists (
      select 1
        from public.employer_admins ea
        join public.students s on s.employer_id = ea.employer_id
       where ea.auth_user_id = auth.uid()
         and s.id = discovery_task_responses.student_id
    )
  );

-- ─── 5. discovery_learning_signals (Phase 0b.4 — ahead of time) ─────────────
-- Behavioural learning-style observations keyed to a discovery session.
-- Phase 0b.4 only; harmless to ship empty until then.

create table if not exists public.discovery_learning_signals (
  id uuid primary key default gen_random_uuid(),
  discovery_session_id uuid not null
    references public.discovery_sessions(id) on delete cascade,
  signal_type text not null check (signal_type in (
    'feedback_engagement',     -- which feedback panel they chose
    'explanation_format',      -- which explanation tab they used
    'pacing'                   -- time deltas between tasks
  )),
  signal_json jsonb not null,
  observed_at timestamptz not null default now()
);

create index if not exists discovery_learning_signals_session_idx
  on public.discovery_learning_signals (discovery_session_id, signal_type);

alter table public.discovery_learning_signals enable row level security;

-- Students can read their own signals (signals join via discovery_sessions
-- → student_id). Insert is service-role only — these are observed by
-- the app, not user-submitted.
drop policy if exists "discovery_learning_signals_self_select"
  on public.discovery_learning_signals;
create policy "discovery_learning_signals_self_select"
  on public.discovery_learning_signals
  for select to authenticated
  using (
    exists (
      select 1 from public.discovery_sessions ds
      where ds.id = discovery_learning_signals.discovery_session_id
        and ds.student_id = auth.uid()
    )
  );
